#!/bin/bash
set -eux -o pipefail

ghc_warnings=(
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
)
ghc_options=(${ghc_warnings[*]} -Werror)

${STACK:-stack} test --ghc-options="${ghc_options[*]}" "$@"
