steps:
  - imports:
      align: global
      pad_module_names: false
  - language_pragmas:
      align: false
      style: compact
  - trailing_whitespace: {}
language_extensions:
  - DataKinds
  - ExistentialQuantification
  - ExplicitNamespaces
  - FlexibleContexts
  - MultiParamTypeClasses
