resolver: lts-13.10

packages:
  - ff
  - ff-core
  - ff-qt
  - ff-test

extra-deps:
  # ff-core:
  - crdt-10.4
  - github-0.21
  - ron-0.6
  - ron-rdt-0.5
  - ron-schema-0.5
  - ron-storage-0.6

  # ff-test:
  - tasty-hedgehog-0.2.0.0

# reduce some deps?
# flags: {comonad: {contravariant: False}}
