resolver: lts-21.25

packages:
  - ff
  - ff-brick
  - ff-core
  - ff-qtah
  - ff-test

extra-deps:
  # ff-core:
    # - ron-0.10
    # - ron-rdt-0.10
    # - ron-schema-0.9.1
    # - ron-storage-0.11
    - github: ff-notes/ron
      commit: a842c13db0dfc7b56987f50a4bebfc898df7c569  # 2026-03-16
      subdirs: [ron, ron-rdt, ron-schema, ron-storage]
  # ff-qtah
    - hoppy-generator-0.9.0
    - hoppy-runtime-0.9.0
    - hoppy-std-0.9.0
    # - qtah-cpp-qt6-0.9.1
    # - qtah-generator-0.9.1
    # - qtah-qt6-0.9.1
    - git: https://git.sr.ht/~cblp/qtah
      commit: dc830718ca0be46f1fb7408f237a5b3d0aae26a5  # 0.9.1 + cblp's patches
      subdirs: [qtah-cpp, qtah-generator, qtah]
  # ff-test
    - cmark-0.6.1

docker:
  enable: false
  image: ff-ubuntu-16.04
