resolver: lts-24.30

packages:
  - ff
  - ff-brick
  - ff-core
  - ff-test

extra-deps:
  # ff-core:
    # - ron-0.10
    # - ron-rdt-0.10
    # - ron-schema-0.9.1
    # - ron-storage-0.11
    - github: ff-notes/ron
      commit: 43cdd3efb778fb7063f43601e2e9496ff57efb02  # 2026-03-15
      subdirs: [ron, ron-rdt, ron-schema, ron-storage]

docker:
  enable: false
  image: ff-ubuntu-16.04
