resolver: lts-19.33

packages:
  - ff
  - ff-core
  # - ff-gtk
  # - ff-qtah
  - ff-test

extra-deps:
  # ff-core:
    - github-0.27
    # - ron-0.10
    # - ron-rdt-0.10
    # - ron-schema-0.9.1
    # - ron-storage-0.11
    - git: https://github.com/ff-notes/ron.git
      commit: 61a1c4fdba4534b1b863771e94760d856889a9f8 # master 2025-05-24
      subdirs: [ron, ron-rdt, ron-schema, ron-storage]
    - shellwords-0.1.2.2

  # ff-gtk:
    # - gi-gtk-declarative-0.7.0
    # - gi-gtk-declarative-app-simple-0.7.0

  # github:
    # - binary-instances-1

  # ff-qtah:
    # - haskell-src-1.0.3.1
    # - hoppy-generator-0.8.0
    # - hoppy-runtime-0.8.0
    # - hoppy-std-0.8.0
    # - qtah-cpp-qt5-0.8.0
    # - qtah-generator-0.8.0
    # - qtah-qt5-0.8.0
    # - git: https://gitlab.com/khumba/qtah.git
    #   commit: b8e9492cb7c2ccd7c3cb7308c9d1495770b0198d  # tag: release-0.8.0
    #   subdirs: [qtah, qtah-cpp, qtah-generator]

docker:
  enable: false
  image: ff-ubuntu-16.04

nix:
  packages: [zlib qt5.qtbase gtk3 gobject-introspection]
