resolver: lts-24.0

packages:
  - ff
  - ff-brick
  - ff-core
  - ff-test

extra-deps:
  # ff-core:
    # - ron-0.10
    # - ron-rdt-0.10
    # - ron-schema-0.9.1
    # - ron-storage-0.11
    - github: ff-notes/ron
      commit: f71fb5c649fdf3cb96a311c8ca8dd8474749bd37  # ron-0.13
      subdirs: [ron, ron-rdt, ron-schema, ron-storage]

docker:
  enable: false
  image: ff-ubuntu-16.04
