resolver: lts-12.0

packages:
  - ff
  - ff-core
  - ff-upgrade

extra-deps:
  # crdt-test:
    - QuickCheck-GenT-0.2.0
  # ff:
    - crdt-10.2
  # ff:test:
    - git: https://github.com/cblp/crdt.git
      commit: '2b6d790'  # 'v10.2' + 2018-07-06
      subdirs:
        - crdt-test
