resolver: lts-13.20

packages:
  - ff
  - ff-core
  - ff-gtk
  - ff-qt
  - ff-test

extra-deps:
  # ff-core:
  - crdt-10.4
  - github-0.21
  - ron-0.6
  - ron-rdt-0.6
  - ron-schema-0.6
  - ron-storage-0.7

  # ff-gtk:
  - gi-gtk-declarative-0.4.2
  - gi-gtk-declarative-app-simple-0.4.1

  # ff-test:
  - tasty-hedgehog-0.2.0.0

# reduce some deps?
# flags: {comonad: {contravariant: False}}

docker:
  enable: false
  image: ff-ubuntu-16.04
