resolver: lts-21.25

packages:
  - ff
  - ff-brick
  - ff-core
  - ff-qtah
  - ff-test

extra-deps:
  # ff-core:
    # - ron-0.10
    # - ron-rdt-0.10
    # - ron-schema-0.9.1
    # - ron-storage-0.11
    # TODO stabilize deps:
    - github: ff-notes/ron
      commit: 3031fd21bc5c0bb02cb8acbd39840ebf8c3ebbca  # 2026-03-22
      subdirs: [ron, ron-rdt, ron-schema, ron-storage]
  # ff-qtah
    - hoppy-generator-0.9.0
    - hoppy-runtime-0.9.0
    - hoppy-std-0.9.0
    # - qtah-cpp-qt6-0.9.1
    # - qtah-generator-0.9.1
    # - qtah-qt6-0.9.1
    # TODO stabilize deps:
    - git: https://git.sr.ht/~cblp/qtah
      commit: 64645f0882fa74faa49a3881debf80af007a7425  # 0.9.1 + cblp's patches
      subdirs: [qtah-cpp, qtah-generator, qtah]
  # ff-test
    - cmark-0.6.1

docker:
  enable: false
  image: ff-ubuntu-16.04
