name: ff
version: '0.8'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

executable:
  main: Main
  other-modules: Paths_ff
  ghc-options: -rtsopts

dependencies:
  # global
  - async
  - base
  - directory
  - extra
  - filepath
  - gitrev
  - mtl
  - pager
  - prettyprinter
  - terminal-size
  - text
  - time

  # organization
  - ron

  # project
  - ff-core
