name: ff
version: '0.6'
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

executable:
  main: Main
  other-modules: Paths_ff
  ghc-options: -rtsopts

dependencies:
  # global
  - async
  - base
  - crdt
  - directory
  - extra
  - filepath
  - gitrev
  - mainland-pretty
  - mtl
  - pager
  - stm
  - terminal-size
  - text
  - time

  # organization
  - ron-storage

  # project
  - ff-core
