#!/bin/bash
set -eux -o pipefail

ghc_warnings=(-Wall -Wincomplete-record-updates -Wincomplete-uni-patterns)
ghc_options=(${ghc_warnings[*]} -Werror)

${STACK:-stack}                           \
    test                                  \
        --ghc-options="${ghc_options[*]}" \
        --haddock                         \
        --no-haddock-deps                 \
        "$@"
