name: ff-core
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    # global
    - aeson
    - aeson-pretty
    - blaze-html
    - bytestring
    - containers
    - crdt
    - data-default-class
    - directory
    - errors
    - extra
    - filepath
    - github
    - hashable
    - mainland-pretty
    - mtl
    - optparse-applicative
    - process
    - random
    - scotty
    - semigroups
    - stm
    - temporary
    - text
    - time
    - typed-process
    - unordered-containers
    - vector
    - warp
    - yaml

    # organization
    - ron
    - ron-storage
  source-dirs: lib

tests:
  features:
    dependencies:
      - blaze-html
      - interpolate
    main: Features.hs

dependencies:
  - base
