name: ff-core
copyright:
  2018 Yuriy Syrovetskiy, Nikolay Loginov

library:
  dependencies:
    - aeson
    - aeson-pretty
    - blaze-html
    - bytestring
    - containers
    - crdt
    - directory
    - errors
    - filepath
    - github
    - mainland-pretty
    - mtl
    - optparse-applicative
    - process
    - random
    - scotty
    - semigroups
    - stm
    - temporary
    - text
    - time
    - typed-process
    - unordered-containers
    - vector
    - yaml
  source-dirs: lib
  other-modules:
    - FF.Types.Internal

tests:
  test:
    dependencies:
      - aeson
      - containers
      - crdt
      - crdt-test
      - errors
      - filepath
      - github
      - mtl
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-th
      - text
      - time
      - unordered-containers

      - ff-core

    main: Main
    source-dirs: test

  features:
    dependencies:
      - blaze-html
      - interpolate
    main: Features.hs

dependencies:
  - base
