name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TASTY_TIMEOUT: 20s

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
      #   cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key:
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Compile and test
      run:
        stack --system-ghc --no-install-ghc
        test
          --pedantic
          --ghc-options=-Wincomplete-record-updates
          --ghc-options=-Wincomplete-uni-patterns
          --ghc-options=-Wredundant-constraints
